const gifFileIds=
[   {BIGBUY_IMAGE1:"BAACAgEAAxkDAAPEYkedAVufjBaXJmVxVbQYNOUlFmkAAlEIAAIteEBG9vl8ljQiz0QjBA"},
    {BIGBUY_IMAGE2:"CgACAgEAAxkDAAPFYkedAlrc1HhuA5N9zFLktt6Hwc8AAlIIAAIteEBGugqND5Rs9b0jBA"},
    {BIGBUY_IMAGE3:"BAACAgEAAxkDAAPGYkedBLx_ixJ5HK6DA8heL1ND9DQAAlMIAAIteEBG7unx4Gv0_csjBA"},
    {BIGBUY_IMAGE4:"CgACAgEAAxkDAAPHYkedBoF1kokP1sQ7QNMlMfnZNfoAAlQIAAIteEBGpeSJAeYv9okjBA"},
    {BIGBUY_IMAGE5:"CgACAgEAAxkDAAPIYkedCKZVa3OYLkwjDmpLBw4Rv7gAAlUIAAIteEBGQo3UtBPiDDUjBA"},
    {BIGBUY_IMAGE6:"CgACAgEAAxkDAAPJYkedCXcGau9u-fV8pv_mGhercpUAAlYIAAIteEBGqM3CAt81WOUjBA"},
    {BIGBUY_IMAGE7:"CgACAgEAAxkDAAPKYkedCyV39GZijV5nvewEltu63xUAAlcIAAIteEBGWeO-Gopzt74jBA"},
    {BIGBUY_IMAGE8:"CgACAgEAAxkDAAPLYkedDXuH3c5wM5wJ950TiQdcjl0AAlgIAAIteEBGD4yCPKCs290jBA"},
    {REGBUY_IMAGE1:"CgACAgEAAxkDAAPMYkedDmih1SmwkvDXHyHoczTGAAHJAAJZCAACLXhARuRvUxnHBQGPIwQ"},
    {REGBUY_IMAGE2:"CgACAgEAAxkDAAPNYkedEDI2Od47tP1L0cXzufks3XwAAloIAAIteEBGyOCSmkzE5agjBA"},
    {REGBUY_IMAGE3:"CgACAgEAAxkDAAPOYkedERXj_b2H_z1Nr69XmXQl9MQAAlsIAAIteEBGRIRSviBbt-MjBA"},
    {REGBUY_IMAGE4:"CgACAgEAAxkDAAPPYkedEtfjCvSfDqbtDKIlWQYmbvsAAlwIAAIteEBG6i4ewULAR10jBA"}    ]
